language: java
sudo: false
install: true
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
jdk:
  - openjdk8


addons:
  sonarcloud:
    organization: vaisman-github
    token: dddcdc1ae278f18e809356e022782afb2507e8ec

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'