language: java
sudo: false
install: true
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
jdk:
  - openjdk8


addons:
  sonarcloud:
    organization: vaisman-github
    token:
      secure: 5692729683a25c5f440ab434d3cf29a6a8a96745
